version: '3.8'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: yarn start:client
    depends_on:
      - server
    networks:
      - decalthon

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
    command: yarn start:server
    networks:
      - decalthon

networks:
  decalthon:
    driver: bridge
