version: "3.8"
services:
  database:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2023
      POSTGRES_DB: nestjs
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nestjs-demetra-systems-zero
  adminer:
    image: adminer:latest
    container_name: adminer-db
    restart: always
    ports:
      - 8080:8080
    networks:
      - nestjs-demetra-systems-zero
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    networks:
      - nestjs-demetra-systems-zero
networks:
  nestjs-demetra-systems-zero:
    driver: bridge
volumes:
  postgres:
