version: "3.8"
services:
  mongodb:
    image: mongo:4.4-focal
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb:/var/lib/mongodb/data
    networks:
      - nestjs-deniko-zero

  mongo-express:
    image: mongo-express:latest
    container_name: mongodb-express
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${DBE_PORT}:${DBE_PORT}
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=${DB_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${DATABASE_URL}
    networks:
      - nestjs-deniko-zero

  redis:
    image: redis:latest
    container_name: redis
    env_file: ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - nestjs-deniko-zero

networks:
  nestjs-deniko-zero:
    driver: bridge
volumes:
  mongodb:
