version: "3.8"
services:
  mongodb:
    image: mongo:4.4-focal
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=2023
      - MONGO_INITDB_DATABASE=whatsapp
    ports:
      - 27017:27017
    volumes:
      - mongodb:/var/lib/mongodb/data
    networks:
      - nestjs-deniko-zero

  mongo-express:
    image: mongo-express:latest
    container_name: mongodb-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongodb
      - ME_CONFIG_MONGODB_ADMINPASSWORD=2023
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=mongodb
      - ME_CONFIG_BASICAUTH_PASSWORD=2023
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:2023@localhost:27017/whatsapp?authSource=admin&directConnection=true
    networks:
      - nestjs-deniko-zero

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - nestjs-deniko-zero

networks:
  nestjs-deniko-zero:
    driver: bridge
volumes:
  mongodb:
